"""Per-slide condensed speaker notes embedded into the .pptx via python-pptx.

The canonical, fully-elaborated speaker notes (with timers, stage directions,
Q&A prep) live in ../notes/SPEAKER-NOTES-ARCHITECT-EXTERNAL.md. This file is
the trimmed presenter prompt shipped INSIDE the deck.
"""

SPEAKER_NOTES: dict[int, str] = {
    1: (
        "Open with the observation, not the product 'OCM'.\n"
        "Any release in the last six months: images, charts, configs, SBOMs - each named differently, each signed differently, if at all.\n"
        "You shipped pieces. Nothing carried the release.\n"
        "That is the gap to close in the next thirty minutes.\n"
        "No brand pitch yet - the deck does that at the end."
    ),
    2: (
        "Why the existing toolbox does not compose. Three artifact types, three identity shapes:\n"
        "• OCI image - `repo:tag` or `repo@sha256:…`. Mirror it, every downstream reference must be rewritten.\n"
        "• Helm chart - repo URL + chart name + version. Move the repo, every `helm install` breaks.\n"
        "• SBOM - no stable identifier of its own. Tied by filename or referrer; repackage and it dangles.\n"
        "Calibration for COSIGN (which can update the digest after explicit `cosign copy`): keep signing each piece. What is missing is a name for the release as one unit, signable, verifiable in a sovereign zone with no callback.\n"
        "Diagnosis: identity is bound to location."
    ),
    3: (
        "The conceptual fulcrum. Let it breathe. OCM separates three things the existing tools fuse:\n"
        "• Component identity - DNS-style name plus SemVer. Globally unique, location-agnostic. No registry in the name.\n"
        "• Digest - SHA-256 over each resource. Computed at pack time. This is what we sign.\n"
        "• Access - type plus fetch fields (`OCIImage/v1`, `Helm/v1`, `LocalBlob/v1`). Where the bytes currently live.\n"
        "Promote EU -> US -> air-gapped CTF and DEV -> STAGING -> PROD : identity stays, digest stays, only access is rewritten. Signature still verifies - anywhere.\n"
        "Move the artifact. The digest stays. Only the access changes. That is the whole trick."
    ),
    4: (
        "Two jobs: pre-empt 'what does this replace?' and define the noun 'COMPONENT' the rest of the deck rests on.\n"
        "OCM is not a replacement for OCI, Helm, cosign, sigstore, or your SBOM tooling. It WRAPS them — adds one envelope signature over the whole release, sitting on top of whatever signatures the individual artifacts already carried.\n"
        "• Any format - Helm stays Helm, OCI stays OCI, configs stay configs. The artifact `type:` is free-form, so an OCM component already carries SBOMs, npm packages, maven artifacts and anything else your team produces today - access is via `File/v1` or `LocalBlob/v1`. Dedicated `NPM/v1` and `Maven/v1` access types are roadmap (Maven epic ocm-project#836; NPM targeted before first GA at end of 2026).\n"
        "• Any location - name and version do not encode a registry. Move it; the name stays.\n"
        "• One signature - covers every digest in the component. The whole release is one signed unit.\n"
        "Q&A backup on cosign / sigstore / OCI 1.1 referrers: We don't replace per-artifact signatures - they travel inside the component. OCM adds a release-level envelope: one signature over the canonicalized component descriptor that covers the digests of every resource. If you cosign-sign every image and ship a sigstore bundle per chart today, keep doing that - OCM signs the wrapper above them.\n"
        "A component is the unit you sign, transport, and deploy. Hold the noun."
    ),
    5: (
        "First YAML the audience sees. Walk it like you would for a colleague - eighteen lines, hand-written.\n"
        "• `components` - list, usually one. Name is DNS-style; version is SemVer.\n"
        "• `provider` - metadata, required.\n"
        "• `resources` - every artifact in the release. Two ways in:\n"
        "  ▪ `input:` - by value. Constructor reads the file at pack time, embeds the bytes. Travels in the archive.\n"
        "  ▪ `access:` - by reference. Records a pointer (e.g. `ghcr.io/.../podinfo:6.9.1`), resolves digest now, copies bytes later.\n"
        "Local files and configs tend to be input; big images tend to be access. Mix freely.\n"
        "CLI if asked: `ocm add cv` against this file, default output a CTF archive."
    ),
    6: (
        "Clarify first: this is generated by `ocm add cv`. You do not hand-edit it. This is what travels.\n"
        "We show one resource - the image - to keep focus on the mechanism. Real components carry many resources and may reference other components; the '...' line stands in for that.\n"
        "• `access` - `OCIImage/v1` with the imageReference pinned to a digest. Kills the repoint-the-tag attack class. Excluded from the canonical form on purpose - transport rewrites it.\n"
        "• `digest` - SHA-256 over the resource bytes. Computed at pack time. Input to the descriptor hash.\n"
        "• `signatures:` - list. Each entry signs ONE hash: the SHA-256 of the canonicalized descriptor. That single hash covers every resource digest. Multiple signatures allowed - dual-sign RSA + Sigstore, verifiers pick.\n"
        "Three things to land. Signed: the descriptor hash - so one signature covers every artifact in the component. Not signed: the access fields - so transport can rewrite them freely. The signature still verifies, anywhere.\n"
        "Sign the descriptor hash, not the access. Seven words; whole transport story."
    ),
    7: (
        "Bridge from noun to verb. On slides 5 and 6 you saw the static artifact - what you write and what travels. Now four moves on that artifact.\n"
        "We've covered the first half of two of them already: the constructor (slide 5) is the input to Pack; the descriptor (slide 6) is the output of Pack, the target of Sign, and the unit of Transport.\n"
        "Name the primitive: the signed descriptor is itself an OCI artifact - media type `application/vnd.ocm.software.component-descriptor.v2`. Lives in your registry next to the images. No new infrastructure.\n"
        "Four moves, same flow, every component:\n"
        "• Pack - bundle once, name once.\n"
        "• Sign - one signature covers every digest.\n"
        "• Transport - registry ↔ registry ↔ tarball. Signature survives every hop.\n"
        "• Deploy - controller verifies, resolves digests, applies. No callback upstream.\n"
        "These are lifecycle moves, not CLI verbs. The CLI you'll type is `ocm add cv`, `ocm sign cv`, `ocm transfer cv`, then `kubectl apply` against the Deployer CR. Same four moves, slightly different names. Sovereign cloud, air-gap, customer cluster. Next four slides are the mechanics."
    ),
    8: (
        "Composition is the architectural fact that makes day-2 work.\n"
        "• Service components carry resources - images, charts, configs, SBOMs. Walk the LEFT box: `acme.org/sovereign/notes` and `acme.org/sovereign/postgres`, each with image + chart + `...` (real components carry more - configs, SBOMs - the `...` stands for that).\n"
        "• A product component composes services via `componentReferences:` - name + version, no resources of its own. Walk the RIGHT box: `acme.org/sovereign/product` references both notes and postgres by name and version. Nothing else.\n"
        "• Each service is independently versioned, signed, transferable. The product is a small descriptor that points at them.\n"
        "Real releases are not one big component - they are one product component referencing several services. This is the shape day-2 (slide 12) operates on."
    ),
    9: (
        "Same signed object - the canonical descriptor digest - in all three. How you prove the key is what varies. All three are stable on the v1alpha1 API surface today:\n"
        "• RSA / RSASSA-PSS - bare public-key pinning. The key you already rotate. No PKI required. Trust model: key pinning.\n"
        "• GPG - OpenPGP key material; trust model is the same as RSA Plain (key pinning), just with a different key format. Fits orgs already running web-of-trust keyrings.\n"
        "• Sigstore - keyless via OIDC + Rekor transparency log; trust anchor is your OIDC issuer. Fits CI workloads and any signer that can present an OIDC identity.\n"
        "Three things to land. Same signed object - the canonical descriptor digest. Verifiers can require multiple in parallel (RSA from release team + Sigstore from CI). Pick what your org already runs.\n"
        "Q&A backup on PEM / cert chains: A fourth option exists - RSA with X.509 certificate chain, PEM encoding. Still experimental: the CLI prints `experimental` warnings on every sign and verify. Watch the docs; we'll promote it when the encoding stabilizes.\n"
        "CLI: `ocm sign cv ./archive//github.com/acme/widget:v1.4.2 --signature acme-release-key --private-key ./release-key.pem`. Idempotent."
    ),
    10: (
        "One mechanic, three patterns - covers every delivery topology you will see.\n"
        "• Registry -> Registry - promotion across dev/staging/prod, or cross-cloud GHCR -> ECR. Same digests, every access rewritten.\n"
        "• Registry -> CTF - Common Transport Format. A local archive of blobs + index. Hand-carry across the boundary.\n"
        "• CTF -> Registry - the air-gap import. Archive arrives, `ocm transfer` uploads, access rewrites to local registry, signature verifies locally. No traffic to source.\n"
        "Same command in all three: `ocm transfer cv <src> <dst>`. Access changes; digests do not. Signature covers digests, so it survives every hop. Verification is purely local at the destination - that is the air-gap property."
    ),
    11: (
        "Four CRs, one chain. The controllers verify and apply the component.\n"
        "• Repository - names where component versions live. OCI registry, mounted CTF, S3, local FS.\n"
        "• Component - names a specific component version. Pulls the descriptor and verifies its signature. If verification fails, nothing downstream sees a verified descriptor - the chain stops here.\n"
        "• Resource - picks one artifact from the verified component, by digest: Helm chart, OCI image, raw manifest, blob.\n"
        "• Deployer - applies the resource to the cluster. Resolves image refs and other deploy-time pointers from the verified component descriptor at apply time - that is where localization happens in v2.\n"
        "For the Helm-deploy reference flow, the chain feeds a `ResourceGraphDefinition` that kro reconciles, with Flux applying the resulting `HelmRelease`. The OCM controllers DON'T ship kro or Flux - bring your own. Slide 14 flags this as one of the three honest edges.\n"
        "Q&A backup if asked about Argo: Argo as an alternative to Flux is in flight (docs PR landing soon). Until merged, the documented Helm-deploy path is kro + Flux.\n"
        "Q&A backup on the controller-shaped `ocm transfer`: yes, there's a `Replication` CR for in-cluster repo-to-repo mirroring. Appendix slide 16 covers it."
    ),
    12: (
        "Composition was just defined on slide 8. This slide does ONE job: the day-2 mechanic.\n"
        "The product is `acme.org/sovereign/product`. Day 1 references notes 1.0.0 and postgres 1.0.0, each with its descriptor digest pinned. The notes team ships a patch (1.0.0 -> 1.1.0). The platform team raises the product to 1.1.0 and updates the notes reference (its version AND its digest, because the new notes descriptor hashes differently). Postgres stays - same version, same digest.\n"
        "Commit. The controller pulls the new product descriptor, verifies the signature, resolves the new digests, applies. Notes rolls forward; postgres is untouched.\n"
        "Differentiator framing for security architects: OCM is a release-level envelope. `helm upgrade` upgrades one chart; cosign signs one image. The OCM signature covers the whole release as one unit - every digest in every resource of every referenced component is pinned by the one parent signature. Drift would mean breaking that signature.\n"
        "Q&A backup on forged descriptors: nothing OCM-specific stops a malicious operator from committing a forged descriptor with bumped versions, an attacker's image references, and a re-signed signature using a stolen key. Same threat model as any signed-release system: rotate keys, dual-sign, audit. What OCM gives you is one signature to audit instead of N.\n"
        "Bump the product. The references follow. The cluster cannot drift without breaking the envelope."
    ),
    13: (
        "Two paths to a first OCM component. Both tested in conformance on every release. Both fit an afternoon on a laptop.\n"
        "• From zero - CLI. No cluster needed. Install CLI. Take one component you already ship. Write the constructor. Pack. Sign with RSA. Export as CTF. Carry to a second machine. Import. Verify. Round trip in 30 minutes. Recommend this first.\n"
        "• On your cluster - controllers. Four K8s deployments, helm-install on any cluster. Point at your registry. Apply a Component resource - verified and reconciling.\n"
        "Both paths coexist with what you already run - cosign, Argo, Flux, Kyverno. OCM signs the descriptor; your existing controls stay in place."
    ),
    14: (
        "The slide that earns trust. Deliver straight; do not soften.\n"
        "• Transfer defaults - copies only the descriptor. For air-gap, pass --copy-resources so the bytes travel too. Worth catching in a CI step the first time someone runs an air-gap export.\n"
        "• Controllers v1alpha1 - CRD shapes for Repository/Component/Resource/Deployer are stabilising but still v1alpha1. Pin to specific release tags in your platform installs.\n"
        "• Helm-deploy adds kro + Flux - the OCM controllers don't ship them. The reference Helm-deploy flow is OCM Controllers -> ResourceGraphDefinition -> kro -> Flux/HelmRelease. Three installs, not one. Plan for it.\n"
        "Honest now beats apologetic later. If any edge is a deal-breaker, tell us early."
    ),
    15: (
        "Close with the ask. Three doors, architect-shaped.\n"
        "• Evaluate - `ocm.software`. Read the spec, run the conformance scenario at `conformance/scenarios/sovereign`, judge fit. You will know within an afternoon if OCM fits.\n"
        "• Pilot - `github.com/open-component-model`. Take one product, one team, scoped scope of work. Spec, implementation, conformance suite, roadmap - all in the open.\n"
        "• Engage - community channels on the website. We're stewarding a standard under NeoNephos Foundation governance. The more voices while it's being shaped, the better the standard gets.\n"
        "Not selling OCM. Stewarding it as a multi-vendor standard. Ship the release as one unit. Thank you - questions."
    ),
    16: (
        "APPENDIX — pull only if asked about cluster-side mirroring or 'how do I get a version from one repo into another without running the CLI?'.\n"
        "A fifth controller, `Replication`, sits alongside the four-card chain - not within it. Where the chain delivers content INTO the cluster, Replication transfers a resolved component version FROM one OCM repository TO another. Same descriptor, same digests, fresh access fields.\n"
        "References a source `Component` CR and a target `Repository` CR. When the source's resolved version changes, transfers that version with its full reference graph into the target.\n"
        "Mirrors the behavior of `ocm transfer cv` on the OCM CLI. Records `status.lastTransferredDigest` after each successful run; a later reconciliation seeing the same digest is a no-op.\n"
        "Use cases: delivery pipelines, promotion between environments, air-gap mirroring kept in-cluster rather than on a workstation.\n"
        "Not on the main deck because the four-card chain is the load-bearing story for a 30-minute architect talk. This is the answer to a specific question, not part of the arc."
    ),
}
