name: Publish Helm Input Plugin Component

on:
  push:
    branches:
      - main
    tags:
      - 'bindings/go/helm/v*'
  workflow_dispatch:
    inputs:
      version:
        description: "Component version, e.g., 0.0.1 or 0.0.1-alpha1. Must match existing bindings/go/helm/vX.Y.Z[-suffix] tag without the 'v'. If not set, 'main' is used."
        required: false
        type: string
        default: "main"

jobs:
  build_publish:
    name: Build and Publish Plugin Component
    runs-on: ubuntu-latest
    concurrency:
      group: helm-plugin-publish-${{ github.ref }}
      cancel-in-progress: false
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine version from input
        id: version_input
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          set -euo pipefail
          if [ -z "${{ github.event.inputs.version }}" ]; then
            VERSION="main"
          else          
            VERSION="${{ github.event.inputs.version }}"
            # SemVer (Major.Minor.Patch + optional -suffix)
            if ! [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[A-Za-z0-9._-]+)?$ ]]; then
              echo "❌ Invalid version format: $VERSION"
              exit 1
            fi
            TAG="bindings/go/helm/v$VERSION"
            # Check if tag exists
            if ! git ls-remote --tags origin "refs/tags/$TAG" | grep -q "refs/tags/$TAG$"; then
              echo "❌ Tag $TAG does not exist in the repository."
              exit 1
            fi
          fi

          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "✅ VERSION resolved to: $VERSION"

      - name: Determine version based on ref
        if: ${{ github.event_name != 'workflow_dispatch' }}
        id: version
        run: |
          set -euo pipefail
          if [[ "$GITHUB_REF" == "refs/heads/main" ]]; then
            VERSION="main"
          elif [[ "$GITHUB_REF" == refs/tags/bindings/go/helm/v* ]]; then
            VERSION="${GITHUB_REF#refs/tags/bindings/go/helm/v}"
          else
            echo "Unsupported ref: $GITHUB_REF"
            exit 1
          fi

          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "✅ VERSION resolved from $GITHUB_REF to: $VERSION"

      - name: Setup Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
        with:
          go-version-file: bindings/go/helm/go.mod
          cache-dependency-path: bindings/go/helm/go.sum

      - name: Install Task
        uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x

      - name: Build multi-arch binaries and generate component constructor
        working-directory: bindings/go/helm
        env:
          VERSION: ${{ env.VERSION }}
        shell: bash
        run: |
          set -euo pipefail
          task tmp
          task build:matrix
          task generate/component-constructor
          test -f "./tmp/component-constructor.yaml" || (echo "component-constructor.yaml not found" && exit 1)

      - name: Log in to GHCR
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # TODO: Pin CLI image version once released
      - name: Publish OCM Component Version
        working-directory: bindings/go/helm
        env:
          REPOSITORY: ghcr.io/open-component-model/plugins
          CLI_IMAGE: ghcr.io/open-component-model/cli:main
          WORKDIR: ${{ github.workspace }}/bindings/go/helm
          DOCKER_CONFIG: /home/runner/.docker
        shell: bash
        run: |
          set -euo pipefail
          # Mount docker auth into container to allow ocm to push to GHCR
          docker run --rm \
            -v "${WORKDIR}:${WORKDIR}" \
            -v "${DOCKER_CONFIG}:/root/.docker:ro" \
            -w "${WORKDIR}" \
            "${CLI_IMAGE}" \
            add component-version \
              --repository "${REPOSITORY}" \
              --constructor "./tmp/component-constructor.yaml"

      - name: Summary
        shell: bash
        run: |
          echo "## Published Helm input plugin component version" >> "$GITHUB_STEP_SUMMARY"
          echo "- Version: ${{ env.VERSION }}" >> "$GITHUB_STEP_SUMMARY"
